FROM node:14

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to work directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy rest of the application code to work directory
COPY . .

# Expose port 3000 (adjust as needed)
EXPOSE 3000

# Command to run when container starts
CMD ["npm", "start"]