name: Seminarski-Aplikacija

services:

  backend:
    build: backend/.
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: "backend/back.env"
    networks:
      - app-network

  front:
    build: frontend/.
    container_name: front
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network
    depends_on:
      backend :
        condition: service_started
      db:
        condition: service_healthy
        
  db:
    build: db/.
    container_name: db
    restart: always
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=rootpassword"]
      interval: 10s
      timeout: 10s
      retries: 6
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
