# Use the official Node.js image
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose port 3001 (or the port your app is running on)
EXPOSE 3001

# Command to run the app
CMD ["node", "server.js"]
