FROM mysql:latest

# Environment variables
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=db
ENV MYSQL_USER=student
ENV MYSQL_PASSWORD=student
ENV MYSQL_AUTHENTICATION_PLUGIN=caching_sha2_password

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306

CMD ["mysqld"]