FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=db
ENV MYSQL_USER=student
ENV MYSQL_PASSWORD=student
ENV MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password

COPY init.sql /docker-entrypoint-initdb.d/init.sql

EXPOSE 3306

CMD ["mysqld"]